/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiTwilioStatusRouteImport } from './routes/api/twilio/status'
import { Route as ApiTwilioVoiceRouteImport } from './routes/api/twilio/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRoute = ApiTwilioStatusRouteImport.update({
  id: '/api/twilio/status',
  path: '/api/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceRoute = ApiTwilioVoiceRouteImport.update({
  id: '/api/twilio/voice',
  path: '/api/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/history'
    | '/profile'
    | '/settings'
    | '/api/twilio/status'
    | '/api/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/history'
    | '/profile'
    | '/settings'
    | '/api/twilio/status'
    | '/api/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/history'
    | '/profile'
    | '/settings'
    | '/api/twilio/status'
    | '/api/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ApiTwilioStatusRoute: typeof ApiTwilioStatusRoute
  ApiTwilioVoiceRoute: typeof ApiTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status': {
      id: '/api/twilio/status'
      path: '/api/twilio/status'
      fullPath: '/api/twilio/status'
      preLoaderRoute: typeof ApiTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice': {
      id: '/api/twilio/voice'
      path: '/api/twilio/voice'
      fullPath: '/api/twilio/voice'
      preLoaderRoute: typeof ApiTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ApiTwilioStatusRoute: ApiTwilioStatusRoute,
  ApiTwilioVoiceRoute: ApiTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
